export const MyEmployees = [
  {
    id: 1,
    isAdmin: true,
    firstName: 'Nil',
    lastName: 'Chaudhary',
    designation: 'Owner/Partner',
    inTime: '',
    outTime: '',
    hasLoggedIn: false,
    todaysExpense: 0,
  },
  {
    id: 2,
    isAdmin: false,
    firstName: 'Pihu',
    lastName: 'More',
    designation: 'Owner/Partner',
    inTime: '',
    outTime: '',
    hasLoggedIn: false,
    todaysExpense: 0,
  },
  {
    id: 3,
    isAdmin: false,
    firstName: 'Rajesh',
    lastName: 'Yadav',
    designation: 'Technician',
    inTime: '',
    outTime: '',
    hasLoggedIn: false,
    todaysExpense: 0,
  },
  {
    id: 4,
    isAdmin: false,
    firstName: 'Vinod',
    lastName: 'Kumar',
    designation: 'Welder',
    inTime: '',
    outTime: '',
    hasLoggedIn: false,
    todaysExpense: 0,
  },
  {
    id: 5,
    isAdmin: false,
    firstName: 'Hardik',
    lastName: 'Patel',
    designation: 'Helper',
    inTime: '',
    outTime: '',
    hasLoggedIn: false,
    todaysExpense: 0,
  },
];
